language: java
addons:
  sonarcloud:
    organization: andresfr09
    token:
      secure: WzDxQ22+Pm29i9q3srshZfM4vzlZ20LLoqGVYUntWYa9e/iFg53KoPByPoA4vDh2Ybf0N4P2Tx0Bfi2Cu4ZYqL85Rl8v7QzIiHdCbfH4Coe9wZ8aaB9A26bsJCPXVyufmjy7C/9YMhbiqs/vRhnMOlREv0f18YV5m0M4cJYzzpxv+xzBYq4NBXDzK0n0AKM0B/kQ4xhwj1W8j1EM3Jn0IT8DtBn3dBm8yAgN3ZnMAVNO85PML6PvBo6xRC57tSeaGpBihpKmREMyQbCP5eJY8dumG2lpGpr1JjxwunDRmP+XFo3lzFfQnT+GPC6pevJP6iD2yqQJn2Y//plyPm/g3GOvtAdi0Nqest4RavjHzONUyU03aX6qU0Hy2kzaRbpPzCh+gXmSVy0ZGaJGgKdei7SkQW5arEd5eYNmasMYtE3tQ+afZ2BXvSpl5onusYhPkQy3Nny36eEk1X8/Tx4Nv5laFKuJddG9ixy9vSOeKK+xo5jqF5CjEHGExV53OzKOGNhYtA4c88MCIARl4YnXhMMEkjSxK/dFESEaLNi84B+ztO/8cjCCDO2j1CkXPz/DehFs6GSdpzO9np+Ygez13hPO9PzuEyzBWo/RXd9ZltU2dfReZS/l6a3DygBTmYZgzSf2qGcKEQI9aMom+zumqh0gAC1S+bybVg8jzLNm8TY=
sudo: required
services:
- docker
notifications:
  slack:
    rooms:
      - clandestinos-espacio:T6BMUCJ6HJliKkPoBIVZbSX0#devops
    if: branch = api-rest-feature
    on_success: always
    on_failure: always
  email:
    recipients:
    - andresr1122@gmail.com
    - juanesteban941@gmail.com
    on_success: always
    on_failure: always
before_install:
#- chmod +x mvnw
- chmod +x start_crashtest.sh
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin
  registry.heroku.com
jobs:
  include:
  - stage: deploy
    script: "./start_crashtest.sh"
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/dummy_name -f Dockerfile.dev .
- docker push $DOCKER_USERNAME/dummy_name
- echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
- docker images
- docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
- docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
- docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
- heroku container:push web --app $HEROKU_APP_NAME
- heroku container:release web --app $HEROKU_APP_NAME
