language: java
addons:
  sonarcloud:
    organization: andresfr09
    token:
      secure: WzDxQ22+Pm29i9q3srshZfM4vzlZ20LLoqGVYUntWYa9e/iFg53KoPByPoA4vDh2Ybf0N4P2Tx0Bfi2Cu4ZYqL85Rl8v7QzIiHdCbfH4Coe9wZ8aaB9A26bsJCPXVyufmjy7C/9YMhbiqs/vRhnMOlREv0f18YV5m0M4cJYzzpxv+xzBYq4NBXDzK0n0AKM0B/kQ4xhwj1W8j1EM3Jn0IT8DtBn3dBm8yAgN3ZnMAVNO85PML6PvBo6xRC57tSeaGpBihpKmREMyQbCP5eJY8dumG2lpGpr1JjxwunDRmP+XFo3lzFfQnT+GPC6pevJP6iD2yqQJn2Y//plyPm/g3GOvtAdi0Nqest4RavjHzONUyU03aX6qU0Hy2kzaRbpPzCh+gXmSVy0ZGaJGgKdei7SkQW5arEd5eYNmasMYtE3tQ+afZ2BXvSpl5onusYhPkQy3Nny36eEk1X8/Tx4Nv5laFKuJddG9ixy9vSOeKK+xo5jqF5CjEHGExV53OzKOGNhYtA4c88MCIARl4YnXhMMEkjSxK/dFESEaLNi84B+ztO/8cjCCDO2j1CkXPz/DehFs6GSdpzO9np+Ygez13hPO9PzuEyzBWo/RXd9ZltU2dfReZS/l6a3DygBTmYZgzSf2qGcKEQI9aMom+zumqh0gAC1S+bybVg8jzLNm8TY=
sudo: required
services:
- docker
#deploy:
#  provider: heroku
#  api_key:
#    secure: KHX+GQ4h9J6rwFAOf2iNJDQM3puDGpB3hNtKKgHQKa4TycAw78RCH8ityPXPycj/tgnavT5xCCaaarESEQ7TNEtv8ZR39daSjVpTqxqQ0OnSQvfZ4xc98ya6meN1Zgdz0+nNf+MMVTo9WK427SbwGage4TsPATcAE7vwVf6oJG3lhvN2qnLU4Fe/7mJ/DD8JD+n6IpfFHbIG+Qze71CA0qQ8tiY6Xq5hKyzNNl54wUrxUgny+XBLF6X5mP2zcNnO8+Kz+di6MA9vMPpZFVQshZNW+0uq6XaEXKiRBadHh0LAfbo51d6yAY7SYdfpVZJojE/vCbCAgQQZoYLjRTv06taJmyfX7etePRdpVJNXG10BSAJqpjIJmOxsSAbd6NMwPhDjWWPF1r1IlqQitRUBxfOVEnZyYUicaXThBgPzJ8u8lrwfa/yJ6lNvDWuM/Qrh/MTI2FO2e75cEQjJk2SvgAxkC5VwKvDT9Dx1e+IApynKm1wW+rmQ+bfwS4scL85YiC3BsnwaQEhcOoEoMjymfSmA9OyMtQk6LkJa6GTtL91Cl3OFFEpWV2DUs5XAiCHrnXj2e2jo2lgpxYfBlw+fSDMFs46wyeCbVajDYK4IVeswEvntv6uKSbkNcAUbaOaQf+NnlJasMal5/JIGaiLptc4Di4H/eqvZ0XiacyrRgIk=
#  app: taller1finaldevops
#  on: api-rest-feature
env:
  - $DOCKER_PASSWORD=CsmlsRUSu/43w0/fBBEXA50ouyxsvwwnWRG5M4RjO+OyRM+xOC+zhMW3fP8egyPucOG8SVg+be96ffuhkHq45nSZIseAu2DXhUQ4SeaEGWBKGqji21m4KFfmU0z7H23lhYwVHHIEXNgcMVuUk++uGamMV2fXFqNnNPiD/RpZkFITXyeuP46Nb11j2yWZ7XW5Rp4AGsKjUBXX6EDE47tNOanEGyB/iKIPvEH04TBOwxeCodb9FArs+X++hS9P29Ghu4QCzqmTnSQo8o/Fwv4nv2aAbGAqC4TxTmiQ7pTwf6PrssvjECzECxEwSNgNECyfaVFgA0IiQDWR5ELisjRCcDOlESgVQwZ5GB2XMZMpnjfjGbUEber3GxBWBZuG50QUoy8NzXZKAdc3c6+rrGPxjygPU7s4sGkTXGxauDICPbuJ3IH5/xLacA+JUMosHYScpARVxNa5cyPu8K+wqDiFRXiTZOki25eMfPpsbt3Vgb55lWJV7JhiLPBBMqms31vBXsdUXBwWOaQ+yov5COhqmbIBIEHxFdcJ9NZmI6hevGY66DdT/ugcC6p+PUZrY0reNDdOMvhJobo0jBMxDo30v1AIYGa+b1owDKIPUaqzONwKXegDys20BoK12yo8GVWyHt8e/eZaIk+oETxrWwWeqMlqUH8pZ2AtujuzY/XBors=
  - $DOCKER_USERNAME=Set8jjd0SZdLR7I8kMxiq9ayse/JcdYQNmhGuGdZYjc4/yTtccK74/x1QFFHbfeLHX3DXdhLyXgbycu+IDc3gGlREKp179WU7ZOAwnVDMX94P/vHsbb4AdhqMDpBjTWzn3V1CPWsDbBxtOtj4dvqk7Wk374qeaXunubIhOQK69Wo9TPrbKT7OTOTnuV+ZlrGyyDBBA/gRi04SVASCjupHhxAkWMZvuDyXrWNzQUD5u5GrsqgfFo4ZWwITwWJDGDaHMcCxvuUa41P/RZaHhJdcIYQF3zAMtXus0ixK+rrVBZmGL4Hg4weH3NbuikK7OZhAOXuo9e/B5rfRBtrUCNivdTdit8huPtf95PQFuzD0MaV4zxLGNQYtOaks859rzY2HCPQiW1oMiR020cogs8ssAEKJA3JrUHXV+lGVnMUScMLJxoebCdIw3Szdng54iUQunc7SpztqxnaxVwM3LTK6Yw4gtVpAk24od4VbT2sa4CceO8A0MlmdC3UcJB6HnTM5pExTAyobJHSeZ4/Y5BsRYHr1W609EvOX/CW69V1QaTqkFk3bevsg+K5KdMJaj3x6D3SYHKPKDug5YsyXwljNFYwgWiYEw7Fxl8gIybbNBW49Dk5LmdwdoR5YvWKmEsJNdQt25+ndw+iEF7hd5BgMYswhzvJo5KyOG6T28Rjx+M=
  - $HEROKU_USERNAME=VBAty7N+NfAQQ8mTakaZrNbXW9sTJ5qZjfFyLCmIIdVT48we/1Ee4d9IVRnhBKyr0HT6+CXfUBcIHo1zEWwOMWeKm79hAc5Zff0/WDVL1YMJ2n3V8q7T3vVcOfPIRhvx8SdiCmuFvy/mG9cQEePlgOOIuqrCQTSQKhUygOgUFbzxeq+UykQRSjRLn9OXEoSKY5146ooYXpy+Hyc5xxN5Rd5ljsv3x5ThXBabxo+ngb7bwVOnW5lq1hyqOHQjX3y1vjwgucoYvCztOd7FMuBrjQVo4VlhhwiWQONDD6suPDvu/veqjj3hqCyn4lBHpHB8JeDa7Z02BV1/n9xZLYslwHtHFRZaJtI57flBDB5YXv5COppKoZvcO1VmKD6cRpYpez7YCD9hsWECYjLRDnX/JdgzI1aRhf8eU30xHZAFiaG7EZDSMGqTMMjVAzpqnC66L1MTBKYjZVuGrcd6vBf1kitJXJNmccJVy6zS8CVuxutYfq4zJg8sp7MnNTUReck8spHs+/c8beuDA8OePMh+hJKVHiG1hPSrzltBaru4Un/0mtsTA7NDaUzyeWk7rw/qhBUex3/gvh3NnP2EwTrVBZFI7/Mmmc6wFf/gRYvF/Lvh4vVrZoZd//AmB1DvoDqXND5QsFYI9jM96dRi9mefsTmNOtfkg27pBpxEX/X4H+k=
  - $HEROKU_PASSWORD=O0RNDUgJaw0/GK18kzfzJ3mhjoEJxqs2DoS3/nAYSA1Rl7vJX9BxATxp9dXm323SbYyHytL3yfDkMacOjbDkjAr10P2ERbNwNYzYA5IyvAl8GFxtlVzJiBSYqU7dfFquo7rXDJtp5CEKBtO4j9yJGwpLh4/1AJ8+UcyfDAS3btzFsBC8++sszaGcrm+IeycOzuNC4YJrw2svjYi2u95hmHsziqU5GmwT0bPleoO+rhqExAlQQd9oSp27zvAZNwYuTlmIY29I0vo3NVXbv58V1GdQcLCT0FjLAOOcs0A2QV3Y7cREaJskcVeyYu6mgX4NUmihD5wBX0JTQU3crpkHv2Kel4SnNnUrkKbq29tQRWBbsUV0S1mnoNI/4z9/90Z9KpkgacP+Rozk4gdJ0kRLxpPZnYkq4pHRQxP1a8EFxofqBL5n+42quKov9vewBj3dKKTMwwST/E4c48OHa1fSYuTpdabQ+niNdgzLpUNiTrTpuRwIreDzUW2L1oBq5hGFj5x2CznVH4GI3jQoN37tMNSybxFbiC12g+agpIh/imLuETZ//wt+Y9qk5m3wS5CaPe8r9BC6hs/HAXruDWhgnsWSj7tAnUtH+3Fwz/MmT5VyyW5YdCP3xCX8Yu/CwfaXt7r/N3ZFiL0Ybkx/1yMiOq9KT01NqAfbwn/SbqiXyZA=

before_install:
- chmod +x mvnw
- docker pull openjdk:15
- docker build -t spring-boot-docker .
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
#script:
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#- docker run --name spring-boot-docker spring-boot-docker:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- echo "asdasdasdasd" | docker login -u "asdasd" --password-stdin
  - docker build -t 1037646031/app-name -f Dockerfile.prod .
  #- pushear la imagen del proyecto spring-boot-docker al usuario propio en dockerhub
  - docker push 1037646031/app-name
  #- loguear a heroku con CLI
  #- (
  #  echo "$HEROKU_CREDENTIALS_EMAIL"
  #  echo "$HEROKU_CREDENTIALS_PASSWORD"
  #  ) | heroku login
  #- ("andresr1122@gmail.com" "Kmzwayw1aa..") | heroku login
  - heroku login
  #- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker tag $DOCKER_USERNAME/app-name registry.heroku.com/tallerdevops4f/web
  - docker push 1037646031/app-name
  #- pushear la imagen a heroku vía docker
  #- heroku stack:set container --app tallerdevops4f
  #- heroku container:login
  - heroku container:push web --app tallerdevops4f
  #release app
  - heroku container:release web --app tallerdevops4f



    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #- docker build -t travis-ci-build-stages-demo -f Dockerfile.dev .
    #- docker images
    #- docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
    #- docker build -t juanpablorl/sample-devops-docker -f Dockerfile .
    #- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
    #- docker images
    #- docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
    #- docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
    #- heroku container:push web --app $HEROKU_APP_NAME
    #- heroku container:release



