language: java
addons:
  sonarcloud:
    organization: andresfr09
    token:
      secure: WzDxQ22+Pm29i9q3srshZfM4vzlZ20LLoqGVYUntWYa9e/iFg53KoPByPoA4vDh2Ybf0N4P2Tx0Bfi2Cu4ZYqL85Rl8v7QzIiHdCbfH4Coe9wZ8aaB9A26bsJCPXVyufmjy7C/9YMhbiqs/vRhnMOlREv0f18YV5m0M4cJYzzpxv+xzBYq4NBXDzK0n0AKM0B/kQ4xhwj1W8j1EM3Jn0IT8DtBn3dBm8yAgN3ZnMAVNO85PML6PvBo6xRC57tSeaGpBihpKmREMyQbCP5eJY8dumG2lpGpr1JjxwunDRmP+XFo3lzFfQnT+GPC6pevJP6iD2yqQJn2Y//plyPm/g3GOvtAdi0Nqest4RavjHzONUyU03aX6qU0Hy2kzaRbpPzCh+gXmSVy0ZGaJGgKdei7SkQW5arEd5eYNmasMYtE3tQ+afZ2BXvSpl5onusYhPkQy3Nny36eEk1X8/Tx4Nv5laFKuJddG9ixy9vSOeKK+xo5jqF5CjEHGExV53OzKOGNhYtA4c88MCIARl4YnXhMMEkjSxK/dFESEaLNi84B+ztO/8cjCCDO2j1CkXPz/DehFs6GSdpzO9np+Ygez13hPO9PzuEyzBWo/RXd9ZltU2dfReZS/l6a3DygBTmYZgzSf2qGcKEQI9aMom+zumqh0gAC1S+bybVg8jzLNm8TY=
sudo: required
services:
- docker

before_install:
- chmod +x mvnw
#- docker pull openjdk:15
#- docker build -t spring-boot-docker .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
-
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/dummy_name -f Dockerfile.dev .
  - docker push $DOCKER_USERNAME/dummy_name
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker images
  - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
  - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
  - heroku container:push web --app $HEROKU_APP_NAME
  - heroku container:release web --app $HEROKU_APP_NAME
  ##- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- echo "asdasdasdasd" | docker login -u "asdasd" --password-stdin
  ##- docker build -t 1037646031/app-name -f Dockerfile.dev.prod .
  #- pushear la imagen del proyecto spring-boot-docker al usuario propio en dockerhub
  ##- docker push 1037646031/app-name
  #- loguear a heroku con CLI
  #- (
  #  echo "$HEROKU_CREDENTIALS_EMAIL"
  #  echo "$HEROKU_CREDENTIALS_PASSWORD"
  #  ) | heroku login
  #- ("andresr1122@gmail.com" "Kmzwayw1aa..") | heroku login
  ##- heroku login
  #- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  #- docker tag $DOCKER_USERNAME/app-name registry.heroku.com/tallerdevops4f/web
  #- docker push 1037646031/app-name
  #- pushear la imagen a heroku vía docker
  ##- heroku stack:set container --app tallerdevops4f
  ##- heroku container:login
  ##- heroku container:push web --app tallerdevops4f
  #release app
  ##- heroku container:release web --app tallerdevops4f





